apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pvc-qos
  namespace: bu528-stop-wasting-the-cloud
spec:
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: boinc-pvc
      containers:
      - name: latest
        image: siddharthbakshi/wcg_centos
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: boincurl
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boincurl
        - name: boinckey
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boinckey
        volumeMounts:
          - name: pv
            mountPath: /var/lib/boinc