apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boinc-pvc
  namespace: bu528-stop-wasting-the-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi