apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wcg-daemonset-resource-only
  namespace: bu528-stop-wasting-the-cloud
spec:
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      containers:
      - name: latest
        image: siddharthbakshi/wcg_centos
        ports:
          - containerPort: 8080
        env:
        - name: boincurl
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boincurl
        - name: boinckey
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boinckey
        resources:
          requests:
            cpu: "16"
            memory: 16Gi
        # counts:
        #   requests:
        #     pods: "12"