apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-sec
  namespace: bu528-stop-wasting-the-cloud
spec:
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      nodeName: k007
      containers:
      - name: latest
        image: siddharthbakshi/wcg_centos
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "5Gi"
        env:
        - name: boincurl
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boincurl
        - name: boinckey
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boinckey